#!/usr/bin/env python
"""Generate index.html — the GitHub Pages landing page.

The proposal is linked first, then every report under reports/ as a card (its
<title> is the label, the filename the sub-label). Re-run after adding or
renaming a report; the page is regenerated from what is on disk, so the listing
never drifts from the files.

    python scripts/build_index.py
"""

from __future__ import annotations

import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROPOSAL = "proposal/perception_metrics_proposal.html"
REPORTS_DIR = ROOT / "reports"

_TITLE = re.compile(r"<title>(.*?)</title>", re.IGNORECASE | re.DOTALL)


def title_of(path: Path) -> str:
    """The document <title>, or the bare filename if it has none."""
    match = _TITLE.search(path.read_text(encoding="utf-8"))
    return match.group(1).strip() if match else path.name


def card(href: str, title: str, primary: bool = False) -> str:
    cls = "card primary" if primary else "card"
    href = html.escape(href, quote=True)
    title = html.escape(title)
    return (
        f'      <a class="{cls}" href="{href}">\n'
        f'        <span class="title">{title}</span>\n'
        f'        <span class="file">{href}</span>\n'
        f"      </a>"
    )


def build() -> str:
    if not (ROOT / PROPOSAL).is_file():
        raise FileNotFoundError(f"proposal page missing: {ROOT / PROPOSAL}")
    proposal_card = card(PROPOSAL, title_of(ROOT / PROPOSAL), primary=True)
    reports = sorted(REPORTS_DIR.glob("*.html"))
    if not reports:
        raise FileNotFoundError(f"no reports found under {REPORTS_DIR}")
    report_cards = "\n".join(
        card(f"reports/{path.name}", title_of(path)) for path in reports
    )
    return PAGE.format(proposal_card=proposal_card, report_cards=report_cards)


PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>autoware-ml reports</title>
<style>
  :root {{
    --bg: #f6f7f9; --surface: #ffffff; --border: #e2e6ea; --fg: #1a2027;
    --muted: #5c6773; --accent: #0e7c86; --shadow: 0 1px 3px rgba(16,24,32,.08);
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{
      --bg: #0f1419; --surface: #161b22; --border: #272d36; --fg: #e6edf3;
      --muted: #9aa5b1; --accent: #3fb6c2; --shadow: 0 1px 3px rgba(0,0,0,.4);
    }}
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; background: var(--bg); color: var(--fg);
    font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  }}
  .wrap {{ max-width: 820px; margin: 0 auto; padding: 64px 24px 96px; }}
  h1 {{ font-size: 2rem; margin: 0 0 8px; letter-spacing: -.02em; }}
  .sub {{ color: var(--muted); margin: 0; font-size: 1.05rem; }}
  h2 {{
    font-size: .8rem; text-transform: uppercase; letter-spacing: .08em;
    color: var(--muted); margin: 44px 0 14px; font-weight: 600;
  }}
  a.card {{
    display: flex; align-items: baseline; gap: 14px; text-decoration: none; color: inherit;
    background: var(--surface); border: 1px solid var(--border); border-radius: 10px;
    padding: 16px 18px; margin-bottom: 10px; box-shadow: var(--shadow);
    transition: border-color .15s, transform .15s;
  }}
  a.card:hover {{ border-color: var(--accent); transform: translateY(-1px); }}
  a.card.primary {{ border-left: 3px solid var(--accent); }}
  .card .title {{ font-weight: 600; }}
  .card .file {{
    color: var(--muted); font-size: .82rem; margin-left: auto; white-space: nowrap;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  }}
  footer {{ margin-top: 56px; color: var(--muted); font-size: .82rem; }}
</style>
</head>
<body>
  <div class="wrap">
    <h1>autoware-ml reports</h1>
    <p class="sub">Perception-metrics proposal and model release reports for autoware-ml
      &mdash; 3D detection &amp; segmentation.</p>

    <h2>Proposal</h2>
{proposal_card}

    <h2>Reports</h2>
{report_cards}

    <footer>Generated by <code>scripts/build_index.py</code> &middot; served with GitHub Pages.</footer>
  </div>
</body>
</html>
"""


if __name__ == "__main__":
    (ROOT / "index.html").write_text(build(), encoding="utf-8")
    print(f"wrote {ROOT / 'index.html'}")
